services:
  petclinic:
    image: mtbsoft/petclinic:latest
    ports:
      - "9090:8080"
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=petclinic
      - MYSQL_USER=petclinic
      - MYSQL_PASSWORD=petclinic
    ports:
      - "3306:3306"
